a=str(input('What is your name: '))
x=input('Please input list of your flock size: ')
x=eval(x)
print('Hello, my name is ',a,' and there are my ship sizes: ',x)
print('Now my biggest sheep has size ',max(x)," let's shear it")
